Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,6 +11,10 @@ on:
         required: true
       VPS_HOST:
         required: true
+      DATABASE_URL:
+        required: true
+      TEST_DATABASE_URL:
+        required: true
 
 jobs:
   deploy:
@@ -89,7 +93,7 @@ jobs:
         if: endsWith(github.repository, 'BackEnd')
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
-            cd /home/recipescheduler_host/www/recipescheduler-test/backend
+            cd ${{ steps.deploy_path.outputs.path }}/backend
             echo 'Current directory: '\$(pwd)
             echo 'Directory contents:'
             ls -la
@@ -100,21 +104,22 @@ jobs:
             echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' > .env
             echo 'TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}' >> .env
             alembic upgrade head
-            sudo systemctl restart recipescheduler.service
+            systemctl restart recipescheduler.service
           "
         env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock
-          
+
       - name: Post-deployment tasks (Frontend)
         if: endsWith(github.repository, 'FrontEnd')
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
             cd ${{ steps.deploy_path.outputs.path }}/frontend
-            echo 'Current directory: '$(pwd)
-            echo 'Directory contents: '$(ls -la)
+            echo 'Current directory: '\$(pwd)
+            echo 'Directory contents:'
+            ls -la
             npm install
             npm run build
-            sudo systemctl restart apache2 || echo 'Failed to restart Apache2'
+            systemctl restart apache2 || echo 'Failed to restart Apache2'
           "
         env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock
